fix Tdecode() encoding None error
maurosoria/dirsearch pull request #937
Opened 2021-07-29 08:37 UTC by XinRoom

fix "TypeError: decode() argument 'encoding' must be str, not None" error

Description
---------------

When response.body is not data, `detect(response.body)["encoding"]` will is None.

```
Exception in thread Thread-1:
Traceback (most recent call last):
  File "C:\Program Files\Python38\lib\threading.py", line 932, in _bootstrap_inner
    self.run()
  File "C:\Program Files\Python38\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "D:\dirsearch\lib\core\fuzzer.py", line 235, in thread_proc
    result = Path(path=path, status=status, response=response)
  File "D:\dirsearch\lib\core\path.py", line 28, in __init__
    self.body = response.body.decode(encoding_type) if response.body != "" else ""
TypeError: decode() argument 'encoding' must be str, not None
```

We can only use it when encoding_type is not None.

`self.body = response.body.decode(encoding_type) if encoding_type!=None else response.body.decode()`

Requirements
---------------

- [ ] Add your name to `CONTRIBUTERS.md`
- [ ] If this is a new feature, then please add some additional information about it to `CHANGELOG.md`

2021-07-29 08:54 UTC, shelld3v commented
Hi @XinRoom, this is an unreliable fix, since we use `get_encoding_type` in multiple places. A better one would be in the **lib/utils/fmt.py**:

```python
def get_encoding_type(content):
    return detect(content)["encoding"]
```

Since `detect(content)["encoding"]` will return `None` if we give it an empty bytes object, it should be something like this:

```python
def get_encoding_type(content):
    if not content:
        return "utf-8"
    return detect(content)["encoding"]
```

Because you are the one who found this bug, I will keep this PR open and let you commit those changes😉(please add your name to `CONTRIBUTERS.md` then)

2021-07-29 08:55 UTC, shelld3v requested changes
As mentioned

2021-07-29 09:17 UTC, XinRoom commented
> As mentioned

Thanks, you are right!

2021-07-29 09:19 UTC, shelld3v approved these changes
Thanks :)

2021-07-29 09:19 UTC, merged

2021-07-30 13:48 UTC, hanshou101 commented
It still appears in 
[ commit d85aa0e4a254e566bc08cc5dc88a5510db56efd3 (HEAD -> master, origin/master, origin/HEAD) ]

![image](https://user-images.githubusercontent.com/19248935/127661989-d87717b8-fe2c-48ba-a28e-656798641d06.png)

```bash
Traceback (most recent call last):
  File "/usr/lib/python3.9/threading.py", line 954, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.9/threading.py", line 892, in run
    self._target(*self._args, **self._kwargs)
  File "/root/desktop/第三方工具/dirsearch/lib/core/fuzzer.py", line 235, in thread_proc
    result = Path(path=path, status=status, response=response)
  File "/root/desktop/第三方工具/dirsearch/lib/core/path.py", line 28, in __init__
    self.body = response.body.decode(encoding_type, errors="ignore")
TypeError: decode() argument 'encoding' must be str, not None
```


Here is my branch info

![image](https://user-images.githubusercontent.com/19248935/127662390-b554912d-6b84-40e9-b319-acb9ead197a6.png)

```
root@HarmonyOS:~/desktop/第三方工具/dirsearch# git branch
* master
```

2021-07-30 14:04 UTC, shelld3v commented
@XinRoom I can't figure out why this happening and give it the best solution, but since this needs to be fixed as fast as possible (due to the severity), can you submit another PR for something like this: 

```python
def get_encoding_type(content):
    content_type = detect(content)["encoding"]
    return content_type if content_type else "utf-8"
```

2021-07-30 14:13 UTC, XinRoom commented
> @XinRoom I can't figure out why this happening and give it the best solution, but since this needs to be fixed as fast as possible (due to the severity), can you submit another PR for something like this:
> 
> ```python
> def get_encoding_type(content):
>     content_type = detect(content)["encoding"]
>     return content_type if content_type else "utf-8"
> ```

suggest:
```python
def get_encoding_type(content):
    return detect(content)["encoding"] or "utf-8"
```

2021-07-30 14:22 UTC, shelld3v commented
@XinRoom Makes sense, I'm dumb

2021-07-30 15:16 UTC, hanshou101 commented
Thank you for your efforts, sir! 
The previous error did not happen again. The progress of the scan has also been greatly advanced.

____

But this time, a new error occurred. I am not sure if it is the same error.

![image](https://user-images.githubusercontent.com/19248935/127673953-3fc4fffc-fadb-4063-9d10-42455d58dfd3.png)


```
Traceback (most recent call last):
  File "/usr/lib/python3.9/threading.py", line 954, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.9/threading.py", line 892, in run
    self._target(*self._args, **self._kwargs)
  File "/root/desktop/第三方工具/dirsearch/lib/core/fuzzer.py", line 240, in thread_proc
    callback(result)
  File "/root/desktop/第三方工具/dirsearch/lib/controller/controller.py", line 487, in match_callback
    added_to_queue = self.add_redirect_directory(path)
  File "/root/desktop/第三方工具/dirsearch/lib/controller/controller.py", line 647, in add_redirect_directory
    redirect_url = urljoin(self.requester.base_url, path.redirect)
AttributeError: 'Requester' object has no attribute 'base_url'
```

And my git tree info 


![image](https://user-images.githubusercontent.com/19248935/127674087-e058b764-9c64-47c8-8fd2-0fe0554242a5.png)

```
root@HarmonyOS:~/desktop/第三方工具/dirsearch# git log
commit 4e0c6c1d9261e31669d9bf8056ff11dd88ce271b (HEAD -> master, origin/master, origin/HEAD)
Merge: d85aa0e 79c360a
Author: Pham Sy Minh <59408894+shelld3v@users.noreply.github.com>
Date:   Fri Jul 30 21:23:22 2021 +0700

    Merge pull request #942 from XinRoom/patch-1
    
    fix decoding None err

```

____

Judging from the error message, it looks like a new problem caused by another factor. But i am not sure.

However, I can successfully complete the scanned items from  6328 ——> 9730 . This is a huge progress !

Thank you , sir !

2021-07-30 15:20 UTC, shelld3v commented
Hi @hanshou101, sorry so much for this issue, I have already submitted a PR for it yesterday but I can't merge, only @maurosoria can. I pinged him but still haven't had it gets merged yet

2021-08-01 07:07 UTC, shelld3v commented
@hanshou101 Forgot to notify, the fix was merged 💪